#!/bin/bash

#
# a4c_create_orchestrator.bash - creates a Yorc orchestrator in Alien4Cloud
#
# Prerequisite:
#   The Yorc Alien4Cloud plugin has to be registered in Alien4Cloud
#   (see a4c_upload_plugin.bash)
#

a4cURL="http://localhost:8088"
yorcURL="http://localhost:8800"
usage() {
    echo ""
    echo "Usage:"
    echo "a4c_configure_orchestrator [--a4c-url <Alien4Cloud URL>] [--yorc-url <Yorc URL>]"
    echo "   - default A4C URL : $a4cURL"
    echo "   - default Yorc URL: $yorcURL"
}

getJsonval() {
	jsonKey=$1
	jsonContent=$2
    temp=`echo "$jsonContent" | awk -F"[{,:}]" '{for(i=1;i<=NF;i++){if($i~/\042'$jsonKey'\042/){print $(i+1)}}}' | tr -d '"' | sed -n 1p`
    echo $temp
}

POSITIONAL=()
while [[ $# -gt 0 ]]
do
key="$1"

case $key in
    -a|--a4c-url)
    a4cURL="$2"
    shift # past argument
    shift # past value
    ;;
    -y|--yorc-url)
    yorcURL="$2"
    shift # past argument
    shift # past value
    ;;
    -h|--help)
    usage
    exit 0
    ;;
    *)    # unknown option
    POSITIONAL+=("$1") # save it in an array for later
    shift # past argument
    ;;
esac
done
set -- "${POSITIONAL[@]}" # restore positional parameters

# First, login and store the cookie
curl -d "username=admin&password=admin&submit=Login"  \
     --url  $a4cURL/login \
     --dump-header headers \
	 --silent \
     --cookie-jar cookies.a4c

# Get Orchestratror ID
res=`curl --request GET \
         --url $a4cURL/rest/latest/orchestrators?query=Yorc \
         --header 'Accept: application/json' \
         --silent \
         --cookie cookies.a4c`
yorcID=`getJsonval id $res`

if [ -z "$yorcID" ]
then
    echo "Exiting on error getting the Orchestrator ID"
    exit 1
fi

# Configure the orchestrator
curl --request PUT \
         --url $a4cURL/rest/latest/orchestrators/$yorcID/configuration  \
         --header 'Content-Type: application/json' \
         --cookie cookies.a4c \
         --silent \
          --data "{\"urlYorc\": \"$yorcURL\"}" > /dev/null

res=$?
if [ $res -ne 0 ]
then
    echo "Exiting on error configuring the orchestrator in Alien4Cloud"
    exit 1
else
    echo "Orchestrator configured in Alien4Cloud"
fi
