#!/bin/bash

#
# a4c_git_import - Imports an Archive from a Git repository
#
#

a4cURL="http://localhost:8088"
repositoryUrl="https://github.com/ystia/yorc-a4c-plugin.git"
branch="develop"
subPath="tosca-samples/org/ystia/yorc/samples/vision"

usage() {
    echo ""
    echo "Usage:"
    echo "a4c_git_import [--a4c-url <Alien4Cloud URL>] [--repository <URL>]"
    echo "               [--branch <branch>] [--path <sub-path>]"
    echo "   - default A4C URL    : $a4cURL"
    echo "   - default repository : $repositoryUrl"
    echo "   - default branch     : $branch"
    echo "   - default path       : $subPath"
}

getJsonval() {
	jsonKey=$1
	jsonContent=$2
    temp=`echo "$jsonContent" | awk -F"[{,:}]" '{for(i=1;i<=NF;i++){if($i~/\042'$jsonKey'\042/){print $(i+1)}}}' | tr -d '"' | sed -n 1p`
    echo $temp
}

POSITIONAL=()
while [[ $# -gt 0 ]]
do
key="$1"

case $key in
    -a|--a4c-url)
    a4cURL="$2"
    shift # past argument
    shift # past value
    ;;
    -r|--repository)
    repositoryUrl="$2"
    shift # past argument
    shift # past value
    ;;
    -b|--branch)
    branch="$2"
    shift # past argument
    shift # past value
    ;;
    -p|--path)
    subPath="$2"
    shift # past argument
    shift # past value
    ;;
    -h|--help)
    usage
    exit 0
    ;;
    *)    # unknown option
    POSITIONAL+=("$1") # save it in an array for later
    shift # past argument
    ;;
esac
done
set -- "${POSITIONAL[@]}" # restore positional parameters

# First, login and store the cookie
curl -d "username=admin&password=admin&submit=Login"  \
     --url  $a4cURL/login \
     --dump-header headers \
	 --silent \
     --cookie-jar cookies.a4c

# Import Git repository
response=`curl --request POST \
         --url $a4cURL/rest/latest/csarsgit \
         --header 'Content-Type: application/json' \
         --cookie cookies.a4c \
         --silent \
          --data "{\"importLocations\": [{\"branchId\": \"$branch\", \"subPath\": \"$subPath\"}], \"repositoryUrl\": \"$repositoryUrl\"}"`

res=$?
if [ $res -ne 0 ]
then
    echo "Exiting on error defining git location at $repositoryUrl, branch $branch, path $subPath : $response"
    exit 1
fi

csarID=`getJsonval data $response`
if [ -z "$csarID" ]
then
    echo "Exiting on error getting the ID for the imported archive"
    exit 1
fi

echo "Archive created, proceeding to the import..."

# Proceed to the import
response=`curl --request POST \
         --url $a4cURL/rest/latest/csarsgit/$csarID \
         --header 'Content-Type: application/json' \
         --cookie cookies.a4c \
         --silent \
          --data "{}"`

res=$?
if [ $res -ne 0 ]
then
    echo "Exiting on error proceeding to the import of the archive : $response"
    exit 1
fi

echo "Archive imported"
