#!/bin/bash

#
# a4c_deploy_application - Deploys an application
# Prerequisites : the application has been created, input parameters provided
#                 and a location where to deploy the application was selected
#

a4cURL="http://localhost:8088"
applicationName=""
synchronous=true
timeoutSeconds=600
usage() {
    echo ""
    echo "Usage:"
    echo "a4c_deploy_application [--a4c-url <Alien4Cloud URL>] "
    echo "                       --application <Application Name>"
    echo "                       [ [--asynchronous] | [--timeout <Wait time in seconds>] ]"
    echo "   - default A4C URL : $a4cURL"
    echo "   - default timeout : $timeoutSeconds seconds"
}

getJsonval() {
	jsonKey=$1
	jsonContent=$2
    temp=`echo "$jsonContent" | awk -F"[{,:}]" '{for(i=1;i<=NF;i++){if($i~/\042'$jsonKey'\042/){print $(i+1)}}}' | tr -d '"' | sed -n 1p`
    echo $temp
}

POSITIONAL=()
while [[ $# -gt 0 ]]
do
key="$1"

case $key in
    -a|--a4c-url)
    a4cURL="$2"
    shift # past argument
    shift # past value
    ;;
    -n|--application)
    applicationName="$2"
    shift # past argument
    shift # past value
    ;;
    -s|--asynchronous)
    synchronous=false
    shift # past argument
    ;;
    -t|--timeout)
    timeoutSeconds=$2
    shift # past argument
    ;;
    -h|--help)
    usage
    exit 0
    ;;
    *)    # unknown option
    POSITIONAL+=("$1") # save it in an array for later
    shift # past argument
    ;;
esac
done
set -- "${POSITIONAL[@]}" # restore positional parameters

if [ -z "$applicationName" ]
then
    echo "Error: missing mandatory parameter application name"
    usage
    exit 1
fi

# First, login and store the cookie
curl -d "username=admin&password=admin&submit=Login"  \
     --url  $a4cURL/login \
     --dump-header headers \
	 --silent \
     --cookie-jar cookies.a4c

# Get the Application environment ID
res=`curl --request POST \
         --url $a4cURL/rest/latest/applications/environments \
         --header 'Content-Type: application/json' \
         --cookie cookies.a4c \
         --silent \
          --data "[\"$applicationName\"]"`
envID=`getJsonval id $res`

if [ -z "$envID" ]
then
    echo "Exiting on error getting the environment ID for Application $applicationName"
    exit 1
fi

# Deploy the application
response=`curl --request POST \
         --url $a4cURL/rest/latest/applications/deployment \
         --header 'Content-Type: application/json' \
         --cookie cookies.a4c \
         --silent \
          --data "{\"applicationEnvironmentId\": \"$envID\", \"applicationId\": \"$applicationName\"}"`

res=$?
if [ $res -ne 0 ]
then
    echo "Exiting on error deploying application $applicationName : $response"
    exit 1
fi

printf "Application $applicationName deployment in progress"

if [ "$synchronous" = false ]
then
    echo ""
    exit 0
fi

# Wait for the end of deployment
start_time="$(date -u +%s)"
finished=false
exitStatus=0
while [ "$finished" = false ]
do
    printf "."
    # Get the deployment status
    response=`curl --request POST \
         --url $a4cURL/rest/latest/applications/statuses \
         --header 'Content-Type: application/json' \
         --cookie cookies.a4c \
         --silent \
          --data "[\"$applicationName\"]"`

    res=$?
    if [ $res -ne 0 ]
    then
        echo -e "\nExiting on error getting the deployment status of application $applicationName : $response"
        exit 1
    fi

    deploymentStatus=`getJsonval environmentStatus $response`
    if [ -z "$deploymentStatus" ]
    then
        echo -e "\nExiting on error getting the deployment status for Application $applicationName"
        exitStatus=1
        finished=true
    elif [ "$deploymentStatus" = "FAILURE" ]
    then
        echo -e "\nExiting on deployment failure for Application $applicationName"
        exitStatus=1
        finished=true
    elif [ "$deploymentStatus" = "DEPLOYED" ]
    then
        echo -e "\nApplication $applicationName deployed"
        exitStatus=0
        finished=true
    else
        end_time="$(date -u +%s)"
        elapsedTime="$(($end_time-$start_time))"
        if [ $elapsedTime -ge $timeoutSeconds ]
        then
            echo -e "\nExiting on timeout waiting for the end of deployment of Application $applicationName"
            exitStatus=1
            finished=true
        else
            sleep 10
        fi
    fi
done

exit $exitStatus